version: '3.8'

services:
  main-server:
    build: ./main-server
    ports:
      - "5000:5000"
    volumes:
      - ./main-server/src:/app/src
    command: /bin/bash
    stdin_open: true
    tty: true
    
  message-client:
    build: ./message-client
    volumes:
      - ./message-client/src:/app/src
    command: /bin/bash
    stdin_open: true
    tty: true
    
  watchdog:
    build: ./watchdog
    volumes:
      - ./watchdog/src:/app/src
    command: /bin/bash
    stdin_open: true
    tty: true